var products = [
    {
        image:"Adidas for Kids.jpg",
        title: "Adidas For Kids",
        price: "10.50",
        sizes: ["13", "12", "1", "2", "3"],
        description: "Some Adidas For Small Child",
        colors: ["Black", "White"],
        materials: ["Polyester, Rubeer, Cotton, other"],
        brand: "Adidas",
        categories: ["Shoes", "Tennis Shoes", "Adidas", "Kids"],
        product_id: "C1900"
    },
    {
        image: "Athletic Baby Shoes.jpg",
        title: "Baby Shoes",
        price: "9.50",
        sizes: ["S", "M", "L"],
        description: "Baby Shoes",
        colors: ["Black", "White", "Gold", "Blue", "Purple", "Red", "Yellow"],
        materials: ["80% Cotton, 20% Polyester"],
        brand: "Oof Outfits",
        categories: ["Shoes", "Comfy", "Baby", "Kids"],
        product_id: "C1901"
    },
    {
        image:"BAby Soft Sole Toddler Booties.jpg",
        title: "Baby Soft Sole Booties",
        price: "9.99",
        sizes: ["S", "M", "L"],
        description: "Some Soft Booties for Toddlers",
        colors: ["Black", "White", "Gold"],
        materials: ["80% Cotton, 20% Polyester"],
        brand: "Oof Outfits",
        categories: ["booties", "soft", "comfortable", "Shoes", "baby"],
        product_id: "C1902"
    },
    {
        image: "beige  black grid pleated skirt.jpg",
        title: "Black Grid Pleated Skirt",
        price: "18.50",
        sizes: ["S", "M", "L", "XL", "XXL"],
        description: "It's a Skirt",
        colors: ["Black", "White", "Gold", "beige", "Purple"],
        materials: ["80% Cotton, 20% Polyester"],
        brand: "Oof Outfits",
        categories: ["Skirt", "comfy", "pleated", "women's"],
        product_id: "C1903"
    },
    {
        image:"Blue 26 Jersey.jpg",
        title: "26 Jersey",
        price: "25.50",
        sizes: ["S", "M", "L", "XL", "XXL"],
        description: "It's a #26 Jersey",
        colors: ["Black", "White", "Blue"],
        materials: ["80% Cotton, 20% Polyester"],
        brand: "Oof Outfits",
        categories: ["Jersey", "comfy", "Sports"],
        product_id: "C1904"
    },
    {
        image:"Bouble Waist Side Butons Pleated Skirt.jpg",
        title: "Waist Pleated Skirt",
        price: "18.50",
        sizes: ["S", "M", "L", "XL", "XXL"],
        description: "Double Waist Side Buttons Pleated Skirt",
        colors: ["Black", "White", "Gold"],
        materials: ["80% Cotton, 20% Polyester"],
        brand: "Oof Outfits",
        categories: ["Skirt", "comfy", "Pleated"],
        product_id: "C1905"
    },
    {
        image:"Bow Skirt and Lace Top.jpg",
        title: "Bow Skirt and Lace Top",
        price: "18.50",
        sizes: ["S", "M", "L", "XL", "XXL"],
        description: "It's a cute baby outfit for girls",
        colors: ["Black", "White", "Gold"],
        materials: ["80% Cotton, 20% Polyester"],
        brand: "Oof Outfits",
        categories: ["skirt", "comfy", "Shirt"],
        product_id: "C1906"
    },
    {
        image:"Casual Black.jpg",
        title: "Casual Dress",
        price: "45.99",
        sizes: ["S", "M", "L", "XL", "XXL", "XXXL"],
        description: "It's a lowkey dress to look casual but nice casual",
        colors: ["Black", "White", "Gold"],
        materials: ["80% Cotton, 20% Polyester"],
        brand: "Oof Outfits",
        categories: ["dress", "comfy", "Off-shoulder"],
        product_id: "C1907"
    },
    {
        image:"Sport Sweatpants.jpg",
        title: "Men's Sweatpants",
        price: "18.50",
        sizes: ["S", "M", "L", "XL", "XXL"],
        description: "Some not so fashionable casual denim shoes for kids",
        colors: ["Black", "White", "Gold"],
        materials: ["80% Cotton, 20% Polyester"],
        brand: "Oof Outfits",
        categories: ["Sweatpants", "Men's", "Athletic"],
        product_id: "C1908"
    },
    {
        image:"Casual Shoes For Men.jpg",
        title: "Casual shoes for men",
        price: "35.50",
        sizes: ["9", "10", "11", "12", "13"],
        description: "Some cas",
        colors: ["Black", "White", "Gold"],
        materials: ["80% Cotton, 20% Polyester"],
        brand: "Oof Outfits",
        categories: ["Casual", "comfy", "men", "Shoes"],
        product_id: "C1909"
    },
    {
        image:"Gothic Funk.jpg",      
        title: "Gothic Funky Jeans",
        price: "18.50",
        sizes: ["S", "M", "L", "XL", "XXL"],
        description: "It's a Short Sleeved Dress",
        colors: ["Black", "White", "Gold"],
        materials: ["80% Cotton, 20% Polyester"],
        brand: "Oof Outfits",
        categories: ["jeans", "Gothic", "Women's"],
        product_id: "C1910"
    },
    {
        image:"Pink Flesh Shoes.jpg",
        title: "Pink Heels",
        price: "18.50",
        sizes: ["S", "M", "L", "XL", "XXL"],
        description: "It's a kids Christmas Skirt",
        colors: ["Black", "White", "Pink"],
        materials: ["80% Cotton, 20% Polyester"],
        brand: "Oof Outfits",
        categories: ["Women's", "Shoes", "Female", "Heels"],
        product_id: "C1911"
    },
    {
        image:"Elegant Buckle Fashion Pumps.png",
        title: "Elegant Buckle Fashion Pumps",
        price: "25.99",
        sizes: ["7", "8", "9", "10", "11"],
        description: "Some fashionable buckle pumps",
        colors: ["Black", "White", "Gold"],
        materials: ["80% Cotton, 20% Polyester"],
        brand: "Oof Outfits",
        categories: ["Shoes", "pumps", "elegant"],
        product_id: "C1912"
    },
    {
        image:"Faded Skinny, Ripped.jpg",
        title: "Faded Ripped Skinny Jeans",
        price: "25.99",
        sizes: ["S", "M", "L", "XL", "XXL"],
        description: "Some faded ripped skinny jeans",
        colors: ["Black", "White", "Gold"],
        materials: ["80% Cotton, 20% Polyester"],
        brand: "Oof Outfits",
        categories: ["faded", "skinny", "Comfy", "Ripped"],
        product_id: "C1913"
    },
    {
        image:"Formal Black Shoes for Men.jpg",
        title: "Formal Shoes for Men",
        price: "35.99",
        sizes: ["9", "10", "11", "12", "13"],
        description: "It's some formal black shoes",
        colors: ["Black", "White", "Brown"],
        materials: ["80% Cotton, 20% Polyester"],
        brand: "Oof Outfits",
        categories: ["formal", "black", "shoes"],
        product_id: "C1914"
    },
    {
        image: "Stripe Dress.jpg",
        title: "Striped Dress",
        price: "18.50",
        sizes: ["S", "M", "L", "XL", "XXL"],
        description: "It's a Lacy dress",
        colors: ["Black", "White", "Gold"],
        materials: ["80% Cotton, 20% Polyester"],
        brand: "DSW",
        categories: ["dress", "comfy", "stripes", "Casual"],
        product_id: "C1915"
    },
    {
        image: "Sweatshirt2.jpg",
        title: "Sweatshirt",
        price: "35.50",
        sizes: ["9", "10", "11", "12", "13"],
        description: "Men's Sweatshirt",
        colors: ["Black", "White", "Gold"],
        materials: ["80% Cotton, 20% Polyester"],
        brand: "Oof Outfits",
        categories: ["sweatshirt", "men", "comfortable"],
        product_id: "C1916"
    },
    {
        image: "Turkey Baby Hat.jpg",
        title: "Turkey Baby Hat",
        price: "10.00",
        sizes: ["One Size Fits All"],
        description: "A small turkey baby hat to warm up your young child's ears",
        colors: ["Black", "White", "Gold"],
        materials: ["80% Cotton, 20% Polyester"],
        brand: "Oof Outfits",
        categories: ["turkey", "comfy", "baby hat"],
        product_id: "C1917"
    },
    {
        image: "Sassy Red Dress.jpg",
        title: "Sassy Red Dress",
        price: "35.99",
        sizes: ["S", "M", "L", "XL", "XXL"],
        description: "It's a sassy red dress",
        colors: ["Black", "White", "Gold"],
        materials: ["80% Cotton, 20% Polyester"],
        brand: "Oof Outfits",
        categories: ["dress", "comfy", "i dunno"],
        product_id: "C1918"
    },
    {
        image: "TOMS Lunata Shoe.png",
        title: "TOMS Lunata Shoes",
        price: "18.50",
        sizes: ["7", "8", "9", "10", "11"],
        description: "Some pink flesh shoes",
        colors: ["Black", "White", "Gold"],
        materials: ["80% Cotton, 20% Polyester"],
        brand: "Oof Outfits",
        categories: ["toms", "Shoes", "heels"],
        product_id: "C1919"
    },
    {
        image: "NIRVANA onesie.jpg",
        title: "NIRVANA Onesie",
        price: "10.50",
        sizes: ["S", "M", "L", "XL", "XXL"],
        description: "It's a onesie for a baby. Gender neutral",
        colors: ["Black", "White", "Gold"],
        materials: ["90% Cotton, 10% Polyester"],
        brand: "Oof Outfits",
        categories: ["Nirvana", "comfy", "i dunno"],
        product_id: "C1920"
    },
    {
        image: "MEts Jersey.jpg",
        title: "Mets Jersey",
        price: "25.50",
        sizes: ["S", "M", "L", "XL", "XXL"],
        description: "It's a Mets Jersey",
        colors: ["Black", "White", "Gold"],
        materials: ["20% Cotton, 80% Polyester"],
        brand: "Oof Outfits",
        categories: ["jersey", "comfy", "shirt", "athletic"],
        product_id: "C1921"
    },
    {
        image: "Liquid Blood.jpg",
        title: "Edgy Candle",
        price: "18.50",
        sizes: ["S", "M", "L", "XL", "XXL"],
        description: "It's an Edgy Candle",
        colors: ["Black", "White", "Gold"],
        materials: ["20% Cotton, 80% Polyester"],
        brand: "Edgy Candles",
        categories: ["Candle", "Edgy", "Cool"],
        product_id: "C1921"
    },
];